### ISSUE TITLE
IndexError: 2 

### ISSUE THREAD

**Issue by Alfah232** [tomchadwin/qgis2web#1026]
Hello,

I have installed the latest version of QGIS (3.28.3) and qgis2web (3.16.0). I have installed it on a 64 bit windows 10 PC.

Every time I am trying to export with leafleat js I receive errors such as:

IndexError: 2 
Traceback (most recent call last):
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 348, in saveMap
    results = writer.write(self.iface,
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 90, in write
    self.preview_file = self.writeLeaflet(
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 261, in writeLeaflet
    useOSMB) = writeVectorLayer(layer, safeLayerName,
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletLayerScripts.py", line 125, in writeVectorLayer
    useShapes) = getLayerStyle(layer, safeLayerName, interactive,
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 63, in getLayerStyle
    pattern) = getSymbolAsStyle(cat.symbol(), markerFolder,
  File "C:\Users/M.Yusup/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletStyleScripts.py", line 180, in getSymbolAsStyle
    sl = symbol.symbolLayer(sl)
IndexError: 2

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.3-Firenze Firenze, c12bcb2f76c 

Any ideas on how to solve this would be much appreciated.

Regards

Joseph

**Comment by andreaordonselli** [comment]
Can you run this test?
Before exporting choose to export to the Desktop folder and retry the export. Let me know if the error is the same.

Otherwise can you attach the qgis project with the data?
Greetings.

**Comment by andreaordonselli** [comment]
I'm closing due to lack of response

**Comment by jamesbe** [comment]
Hi there, I am having this same issue! Any help would be greatly appreciated!
[Single_Map.zip](https://github.com/user-attachments/files/16179437/Single_Map.zip)
 I attached my qgis project.
