### ISSUE TITLE
Outline: simple line crashes Leaflet export

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#11]
If I set the polygon style to Outline:Simple Line for both layers and then export to OL3 I get the effect I want - outlines and no fill.  Exporting to Leaflet results in a error about Leaflet not being able to render that kind of styling:

```    Traceback (most recent call last):
      File "C:/Users/me/.qgis2/python/plugins\qgis2web\maindialog.py", line 138, in saveLeaf
    writeLeaflet("index.html", "", "", "", 600, 400, "canvas extent", "", layers, "show all", "", 0, 0, "", "", "", "", "", "", 15, "", "", "", 0)
      File "C:/Users/me/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 476, in writeLeaflet
    if symbol.symbolLayer(0).brushStyle() == 0:
    AttributeError: 'QgsSimpleLineSymbolLayerV2' object has no attribute 'brushStyle'```

I guess this could all be tweaked in the index.html and CSS files once all the hard work has been done by your plugin.

**Comment by tomchadwin** [comment]
Fixed in master. Can you test, @mixedbredie? Did you also experience this error in qgis2leaf, @pcav? Does this fix it?
