### ISSUE TITLE
Leaflet JSON categorized line fails

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#163]
```
Traceback (most recent call last):
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\maindialog.py", line 117, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\maindialog.py", line 302, in previewLeaflet
json, params, popup)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 242, in writeLeaflet
json, wfsLayers)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 607, in categorizedLayer
visible, count, wfsLayers)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 677, in categorizedLine
categoryStr += categorizedLineStylesScript(symbol, fill_opacity)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletScriptStrings.py", line 436, in categorizedLineStylesScript
weight=symbol.width() * 4,
AttributeError: 'QgsFillSymbolV2' object has no attribute 'width'
```

**Comment by tomchadwin** [comment]
No, this occurred because I had mistakenly applied a fill style to a line layer. Yes, we should catch such errors, but for the moment, we'll close this one as a wontfix.
