### ISSUE TITLE
Layer groups don't work very well at all

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#175]
I don't even know exactly what they do at the moment, but we need to use the Layer Tree API to get it working properly. This will probably break the Leaflet stackLayers() and restackLayers() functions.

**Comment by tomchadwin** [comment]
I've created a branch for this (https://github.com/tomchadwin/qgis2web/tree/nestedLayerGroups). However, I think this change is going to have many ramifications. The very way in which the layers selected for inclusion in the map are passed from the GUI to the export functions seems like it might not work with properly nested groups. As far as I understand it, it passes a list of layers and a list of groups - the structure of the tree is flattened irrevocably in the process.

I need to look at this from a wider perspective - perhaps maindialog's getLayersAndGroups() is not even required, and writeOL() and writeLeaflet() could query the GUI directly for the layer and group info, rather than being passed it in the abstraction which getLayersAndGroups() produces?

**Comment by Randy6668** [comment]
Hi Tom,

Sorry for bringing this issue up, but recently I was attempting to dabble with grouped layers using other plugins: [groupedlayercontrol](https://github.com/ismyrnow/leaflet-groupedlayercontrol) and [styledlayercontrol](https://github.com/davicustodio/Leaflet.StyledLayerControl), since I've not been able to reproduce grouped layers (point layers) onto both leaflet and OL3 like other issues raised up previously. Using their examples worked fine for me, but when I attempt to implement it onto the leaflet map created using qgis2web, the map does not work.
What I'm doing is basically replacing the original control:
```
L.control.layers(baseMaps,
		{'<img src="legend/ElderlyDayCareCentres5.png" /> Elderly Day Care Centres': layer_ElderlyDayCareCentres5,'<img src="legend/CommunityClubs4.png" /> Community Clubs': layer_CommunityClubs4,'<img src="legend/PublicHospitals2.png" /> Public Hospitals': layer_PublicHospitals2,'<img src="legend/PrivateHospitals1.png" /> Private Hospitals': layer_PrivateHospitals1,},
		{collapsed:true}
		).addTo(map);
```
With their's (eg.):
```
var overlays = [{
			groupName : "Social Welfare",
			expanded : true,
			layers    : { 
					"Community Clubs" : layer_CommunityClubs4,
					"Day Care Centres" : layer_ElderlyDayCareCentres5
					}	
                          }, {
			 groupName : "Healthcare",
			 expanded : true,
			 layers    : { 
					"Private Hospitals" 	 : layer_PrivateHospitals1,
					"Public Hospitals"	 : layer_PublicHospitals2		
					}	
                             }, 					 
			];
        
		var options = {
               container_width     : "300px",
               container_maxHeight : "350px", 
               group_maxHeight     : "80px",
               exclusive           : false
		};
	
		L.Control.styledLayerControl(overlays, baseMaps, options).addTo(map);
```
I'm pretty much java illiterate, so qgis2web has been heaven-sent for me. Would really love to get these plugins working with qgis2web to solve the grouped layer issue. So far I've tried to copy portions of the layers (and script) made by qgis2web onto the example codes they provided, but it did not work either. I'm suspecting it has something to do with how qgis2web deploy the layers? I have raised issues with the respective developers but so far there's no reply/solution yet, so I'm wondering if i can get some help here. Thanks so much!

**Comment by tomchadwin** [comment]
@Randy6668 I think the best way to proceed would be for you to upload (or paste the contents of) your qgis2web exported `index.html` file, unmodified. I can then take a look at how to get either of the plugins to group your layers.

**Comment by Randy6668** [comment]
Hi! Thanks so much! Here's the index file, and the [data files](https://www.dropbox.com/s/ftm758xkdot1l1e/test_map_data.rar?dl=0) if you need to check the map!
[index.txt](https://github.com/tomchadwin/qgis2web/files/811213/index.txt)

**Comment by tomchadwin** [comment]
OK, download the `groupedlayercontrol` JS and CSS files into the `/js` and `/css` folders of your qgis2web export respectively. Include them in `index.html`:

```html
        <link rel="stylesheet" type="text/css" href="css/leaflet.groupedlayercontrol.min.css" />
        <script src="js/leaflet.groupedlayercontrol.min.js"></script>
```

Then replace the whole of line 278 (starting `L.control.layers(...`) with:

```javascript
        var groupedLayers = {
            'Hospitals': {
                '<img src="legend/PublicHospitals1.png" /> Public Hospitals': layer_PublicHospitals1,
                '<img src="legend/PrivateHospitals0.png" /> Private Hospitals': layer_PrivateHospitals0
            },
            'Other': {
                '<img src="legend/ElderlyDayCareCentres3.png" /> Elderly Day Care Centres': layer_ElderlyDayCareCentres3,
                '<img src="legend/CommunityClubs2.png" /> Community Clubs': layer_CommunityClubs2
            }
        }
        L.control.groupedLayers(baseMaps, groupedLayers).addTo(map);
```

The whole index.html is now:

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <link rel="stylesheet" href="css/leaflet.css" />
        <link rel="stylesheet" type="text/css" href="css/leaflet.groupedlayercontrol.min.css" />
        <link rel="stylesheet" type="text/css" href="css/qgis2web.css">
        <link rel="stylesheet" href="css/MarkerCluster.css" />
        <link rel="stylesheet" href="css/MarkerCluster.Default.css" />
        <style>
        html, body, #map {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
        }
        </style>
        <title></title>
    </head>
    <body>
        <div id="map">
        </div>
        <script src="js/qgis2web_expressions.js"></script>
        <script src="js/leaflet.js"></script>
        <script src="js/leaflet.groupedlayercontrol.min.js"></script>
        <script src="js/leaflet-heat.js"></script>
        <script src="js/leaflet.rotatedMarker.js"></script>
        <script src="js/OSMBuildings-Leaflet.js"></script>
        <script src="js/leaflet-hash.js"></script>
        <script src="js/Autolinker.min.js"></script>
        <script src="js/leaflet.markercluster.js"></script>
        <script src="data/PrivateHospitals0.js"></script>
        <script src="data/PublicHospitals1.js"></script>
        <script src="data/CommunityClubs2.js"></script>
        <script src="data/ElderlyDayCareCentres3.js"></script>
        <script>
        L.ImageOverlay.include({
            getBounds: function () {
                return this._bounds;
            }
        });
        var map = L.map('map', {
            zoomControl:true, maxZoom:28, minZoom:1
        })
        var hash = new L.Hash(map);
        map.attributionControl.addAttribution('<a href="https://github.com/tomchadwin/qgis2web" target="_blank">qgis2web</a>');
        var bounds_group = new L.featureGroup([]);
        var basemap0 = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
            maxZoom: 28
        });
        basemap0.addTo(map);
        function setBounds() {
            if (bounds_group.getLayers().length) {
                map.fitBounds(bounds_group.getBounds());
            }
        }
        function geoJson2heat(geojson, weight) {
          return geojson.features.map(function(feature) {
            return [
              feature.geometry.coordinates[1],
              feature.geometry.coordinates[0],
              feature.properties[weight]
            ];
          });
        }
        function pop_PrivateHospitals0(feature, layer) {
            var popupContent = '<table>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Name'] !== null ? Autolinker.link(String(feature.properties['Name'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Address'] !== null ? Autolinker.link(String(feature.properties['Address'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Latitude'] !== null ? Autolinker.link(String(feature.properties['Latitude'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Longitude'] !== null ? Autolinker.link(String(feature.properties['Longitude'])) : '') + '</td>\
                    </tr>\
                </table>';
            layer.bindPopup(popupContent);
        }

        function style_PrivateHospitals0() {
            return {
                pane: 'pane_PrivateHospitals0',
                radius: 4.0,
                opacity: 1,
                color: 'rgba(0,0,0,1.0)',
                dashArray: '',
                lineCap: 'butt',
                lineJoin: 'miter',
                weight: 1,
                fillOpacity: 1,
                fillColor: 'rgba(193,244,117,1.0)',
            }
        }
        map.createPane('pane_PrivateHospitals0');
        map.getPane('pane_PrivateHospitals0').style.zIndex = 600;
        map.getPane('pane_PrivateHospitals0').style['mix-blend-mode'] = 'normal';
        var layer_PrivateHospitals0 = new L.geoJson(json_PrivateHospitals0, {
            attribution: '<a href=""></a>',
            pane: 'pane_PrivateHospitals0',
            onEachFeature: pop_PrivateHospitals0,
            pointToLayer: function (feature, latlng) {
                var context = {
                    feature: feature,
                    variables: {}
                };
                return L.circleMarker(latlng, style_PrivateHospitals0(feature))
            }
        });
        bounds_group.addLayer(layer_PrivateHospitals0);
        map.addLayer(layer_PrivateHospitals0);
        function pop_PublicHospitals1(feature, layer) {
            var popupContent = '<table>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Name'] !== null ? Autolinker.link(String(feature.properties['Name'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Address'] !== null ? Autolinker.link(String(feature.properties['Address'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Latitude'] !== null ? Autolinker.link(String(feature.properties['Latitude'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Longitude'] !== null ? Autolinker.link(String(feature.properties['Longitude'])) : '') + '</td>\
                    </tr>\
                </table>';
            layer.bindPopup(popupContent);
        }

        function style_PublicHospitals1() {
            return {
                pane: 'pane_PublicHospitals1',
                radius: 4.0,
                opacity: 1,
                color: 'rgba(0,0,0,1.0)',
                dashArray: '',
                lineCap: 'butt',
                lineJoin: 'miter',
                weight: 1,
                fillOpacity: 1,
                fillColor: 'rgba(131,160,177,1.0)',
            }
        }
        map.createPane('pane_PublicHospitals1');
        map.getPane('pane_PublicHospitals1').style.zIndex = 601;
        map.getPane('pane_PublicHospitals1').style['mix-blend-mode'] = 'normal';
        var layer_PublicHospitals1 = new L.geoJson(json_PublicHospitals1, {
            attribution: '<a href=""></a>',
            pane: 'pane_PublicHospitals1',
            onEachFeature: pop_PublicHospitals1,
            pointToLayer: function (feature, latlng) {
                var context = {
                    feature: feature,
                    variables: {}
                };
                return L.circleMarker(latlng, style_PublicHospitals1(feature))
            }
        });
        bounds_group.addLayer(layer_PublicHospitals1);
        map.addLayer(layer_PublicHospitals1);
        function pop_CommunityClubs2(feature, layer) {
            var popupContent = '<table>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['ADDRESSBLO'] !== null ? Autolinker.link(String(feature.properties['ADDRESSBLO'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['ADDRESSBUI'] !== null ? Autolinker.link(String(feature.properties['ADDRESSBUI'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['ADDRESSPOS'] !== null ? Autolinker.link(String(feature.properties['ADDRESSPOS'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['ADDRESSSTR'] !== null ? Autolinker.link(String(feature.properties['ADDRESSSTR'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['ADDRESSTYP'] !== null ? Autolinker.link(String(feature.properties['ADDRESSTYP'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['NAME'] !== null ? Autolinker.link(String(feature.properties['NAME'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['X_ADDR'] !== null ? Autolinker.link(String(feature.properties['X_ADDR'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Y_ADDR'] !== null ? Autolinker.link(String(feature.properties['Y_ADDR'])) : '') + '</td>\
                    </tr>\
                </table>';
            layer.bindPopup(popupContent);
        }

        function style_CommunityClubs2() {
            return {
                pane: 'pane_CommunityClubs2',
                radius: 4.0,
                opacity: 1,
                color: 'rgba(0,0,0,1.0)',
                dashArray: '',
                lineCap: 'butt',
                lineJoin: 'miter',
                weight: 1,
                fillOpacity: 1,
                fillColor: 'rgba(106,101,151,1.0)',
            }
        }
        map.createPane('pane_CommunityClubs2');
        map.getPane('pane_CommunityClubs2').style.zIndex = 602;
        map.getPane('pane_CommunityClubs2').style['mix-blend-mode'] = 'normal';
        var layer_CommunityClubs2 = new L.geoJson(json_CommunityClubs2, {
            attribution: '<a href=""></a>',
            pane: 'pane_CommunityClubs2',
            onEachFeature: pop_CommunityClubs2,
            pointToLayer: function (feature, latlng) {
                var context = {
                    feature: feature,
                    variables: {}
                };
                return L.circleMarker(latlng, style_CommunityClubs2(feature))
            }
        });
        bounds_group.addLayer(layer_CommunityClubs2);
        map.addLayer(layer_CommunityClubs2);
        function pop_ElderlyDayCareCentres3(feature, layer) {
            var popupContent = '<table>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Name'] !== null ? Autolinker.link(String(feature.properties['Name'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Address'] !== null ? Autolinker.link(String(feature.properties['Address'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Latitude'] !== null ? Autolinker.link(String(feature.properties['Latitude'])) : '') + '</td>\
                    </tr>\
                    <tr>\
                        <td colspan="2">' + (feature.properties['Longitude'] !== null ? Autolinker.link(String(feature.properties['Longitude'])) : '') + '</td>\
                    </tr>\
                </table>';
            layer.bindPopup(popupContent);
        }

        function style_ElderlyDayCareCentres3() {
            return {
                pane: 'pane_ElderlyDayCareCentres3',
                radius: 4.0,
                opacity: 1,
                color: 'rgba(0,0,0,1.0)',
                dashArray: '',
                lineCap: 'butt',
                lineJoin: 'miter',
                weight: 1,
                fillOpacity: 1,
                fillColor: 'rgba(211,164,131,1.0)',
            }
        }
        map.createPane('pane_ElderlyDayCareCentres3');
        map.getPane('pane_ElderlyDayCareCentres3').style.zIndex = 603;
        map.getPane('pane_ElderlyDayCareCentres3').style['mix-blend-mode'] = 'normal';
        var layer_ElderlyDayCareCentres3 = new L.geoJson(json_ElderlyDayCareCentres3, {
            attribution: '<a href=""></a>',
            pane: 'pane_ElderlyDayCareCentres3',
            onEachFeature: pop_ElderlyDayCareCentres3,
            pointToLayer: function (feature, latlng) {
                var context = {
                    feature: feature,
                    variables: {}
                };
                return L.circleMarker(latlng, style_ElderlyDayCareCentres3(feature))
            }
        });
        bounds_group.addLayer(layer_ElderlyDayCareCentres3);
        map.addLayer(layer_ElderlyDayCareCentres3);
        var baseMaps = {};
        var groupedLayers = {
            'Hospitals': {
                '<img src="legend/PublicHospitals1.png" /> Public Hospitals': layer_PublicHospitals1,
                '<img src="legend/PrivateHospitals0.png" /> Private Hospitals': layer_PrivateHospitals0
            },
            'Other': {
                '<img src="legend/ElderlyDayCareCentres3.png" /> Elderly Day Care Centres': layer_ElderlyDayCareCentres3,
                '<img src="legend/CommunityClubs2.png" /> Community Clubs': layer_CommunityClubs2
            }
        }
        L.control.groupedLayers(baseMaps, groupedLayers).addTo(map);
        setBounds();
        </script>
    </body>
</html>
```

**Comment by tomchadwin** [comment]
There is a browser console error, but other than that, it seems to work.

**Comment by tomchadwin** [comment]
And I think I should thank you for showing me that implementing this for Leaflet export in fact will not involve any of the complications I listed above. The export and styling can still be fine using the flattened approach. I can just walk the `layerTree` to build the nested structure and use that plugin you've pointed me towards. Plus, since Leaflet v1, there's no `stackLayers()` or `restackLayers()` to worry about. I'll try to look at this tomorrow. Thanks!

**Comment by Randy6668** [comment]
Oh yes, forgot to thank you! I had to do some minor edits (for some reason I had to remove the .min from the link to the CSS), but both plugins work fine for me now. Would be nice if qgis2web can incorporate these functions too. Thanks!

**Comment by tomchadwin** [comment]
Hrm. Seems that `groupedlayercontrol` is not going to do the job for two reasons:

1. It doesn't cope with ungrouped layers

2. It doesn't handle nested groups

Disappointing. I'll investigate further.

**Comment by stevenhorner** [comment]
I think this is related to the same issue, apologies if this should be a new one.

Whenever I try to use qgis2web with any project containing Layer Groups, QGIS just hangs and gives the following error:

```
An error has occurred while executing Python code: 

AttributeError: 'int' object has no attribute 'keys' 
Traceback (most recent call last):
  File "C:/Users/stevenhorner/.qgis2/python/plugins\qgis2web\maindialog.py", line 331, in saveMap
    feedback=self.feedback)
  File "C:/Users/stevenhorner/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 98, in write
    folder=dest_folder)
  File "C:/Users/stevenhorner/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 244, in writeLeaflet
    extent, feedback)
  File "C:/Users/stevenhorner/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 269, in writeVectorLayer
    popupsOnHover, popup)
  File "C:/Users/stevenhorner/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 433, in getPopups
    field_names = popup.keys()
AttributeError: 'int' object has no attribute 'keys'
```

If I check the output folder the JSON has been created for the layers but no index.html is generated. This is the same for both Leaflet or OL.

I have checked back through some of my old exported maps and I have used the plugin with grouped layers a year ago and it worked then with an old version of both QGIS and qgis2web. I'm currently on the latest version of the plugin and QGIS 2.18.3 Windows version.

Unfortunately almost all my projects have grouped layers

**Comment by tomchadwin** [comment]
@stevenhorner Ah, this is the second instance of this error. I don't know if layer groups are the explanation.

@pcav Can you confirm your project which gives this error has layer groups? If so, are you able temporarily to remove the layer groups, to confirm whether the error disappears?

**Comment by pcav** [comment]
I confirm the project has groups. I'll ask to test without.
Thanks.

**Comment by tomchadwin** [comment]
I've finally reproduced the error. I'll look for a quick workaround, but solving groups overall has to be the final aim. It's the one single biggest remaining important feature lacking in qgis2web. However, it's not easy to fix, for the reasons given above.

**Comment by tomchadwin** [comment]
OK, this still needs much more investigation and work, but can @pcav and @stevenhorner try latest master with layer groups now, and see whether the error has gone?

**Comment by stevenhorner** [comment]
Afraid when I try to install from Master I get the following error when trying to enable it in QGIS. It could be me doing something wrong but just unzipped into a qgis2web folder in my plugins directory:

```
Couldn't load plugin qgis2web due to an error when calling its classFactory() method 

ImportError: No module named parameters 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Steven/.qgis2/python/plugins\qgis2web\__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Steven/.qgis2/python/plugins\qgis2web\qgis2web.py", line 30, in 
    from qgis2webProvider import qgis2webProvider
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Steven/.qgis2/python/plugins\qgis2web\qgis2webProvider.py", line 26, in 
    from qgis2webAlgorithm import exportProject, exportVector, exportRaster
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Steven/.qgis2/python/plugins\qgis2web\qgis2webAlgorithm.py", line 34, in 
    from processing.core.parameters import (ParameterVector,
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named parameters
```

**Comment by tomchadwin** [comment]
You have the Processing plugin enabled?

**Comment by stevenhorner** [comment]
Yes processing is installed and working.

**Comment by tomchadwin** [comment]
@stevenhorner Can you take a look at https://github.com/NaturalGIS/postgis_geoprocessing/issues/15 and see if that helps you? Let us know.

**Comment by stevenhorner** [comment]
Thanks, yes that was the problem with the plugin initializing.  Also now the layers inside the layer groups display in Leaflet, it doesn't group them but at least the layers show. Openlayers just displays a blank map.

I think you have done some more updates to master since I copied it, will test again by downloading the latest master.

**Comment by stevenhorner** [comment]
Re-tested with latest master and happy to report the layers still display. The only problem is that I don't get all the layer options that I would for layers that are not grouped for instance the popup fields and visibility for each layer inside the group when creating the map are not available, just one option to make them the layer group visible. I can turn each layer inside the group on and off on the generated leaflet map.

**Comment by tomchadwin** [comment]
@stevenhorner Thanks for reporting back. The group behaviour you describe is as good as it gets at the moment. The plugin qgis2web is based on (qgis-ol3) was written before plugins could interpret the group structure properly. Adding proper group export is the big change I referred to above.

**Comment by lucacasagrande** [comment]
I just star working on this issue.

**Comment by tomchadwin** [comment]
Thanks, Luca! Summary of my thoughts/knowledge of the issue to date:

1. As you mentioned, make sure you have a final method in the webmap libs to achieve what we need. @walkermatt's OL layer switcher is tightly bound to the map layers, whereas the Leaflet layerControl is not - you add layers to it independently. When I tried to solve this issue, I asked around, but could not find a plugin to do the job on the Leaflet side (https://gis.stackexchange.com/questions/230675/leaflet-v1-plugin-layer-control-for-ungrouped-grouped-and-nested-grouped-laye). If we can find the right Leaflet method, it is likelier to be potentially easier than OL, because only the layer list entries need to be grouped, not the layers themselves, so we don't need to touch the core code which adds the layers to the map. If we can get @stefanocudini's plugin working with Leaflet v1, that might be the best approach (https://github.com/stefanocudini/leaflet-panel-layers). OL is different, as it stands, and I don't know the best approach yet.

2. The way the layers are passed from the GUI hasn't changed from when you coded gis-ol3 (https://github.com/tomchadwin/qgis2web/blob/master/maindialog.py#L534), except that after @nyalldawson's refactoring, the GUI is abstracted from the writing methods ( eg https://github.com/tomchadwin/qgis2web/blob/master/maindialog.py#L201). Hopefully it's clear enough from the code.

As you are aware, this issue could be resulting in an issue experienced by @pcav's client - if he can get at his client's data from Essen, he might be able to demonstrate (I don't know if he has recreated the bug himself, though).

**Comment by lucacasagrande** [comment]
Thanks for the summary Tom. I am now on the OL side, and it seems related to layers name without the count at the end 
https://github.com/tomchadwin/qgis2web/blob/master/olLayerScripts.py#L61

For Leaflet, what do you think if don't use group until there is a solution?

**Comment by tomchadwin** [comment]
You mean the error is related to that? Sounds very likely. If you `enumerate()` the layers in that loop and concat on the count, does that fix it? 

We have two things on this issue: Paolo's bug and full support. Totally happy with *any* progress. No problem if only OL is worked on.

**Comment by tomchadwin** [comment]
Confirmed that @lucacasagrande's work fixes the client-side JS errors I was experiencing. However, @pcav's client's error was server-side, so we'll have to see if that is also now fixed - I assume not.

**Comment by lucacasagrande** [comment]
Should we open a new ticket and close this one?

**Comment by tomchadwin** [comment]
Sure. Go ahead and open a new one.

**Comment by tomchadwin** [comment]
I'm not sure we ever opened another ticket, so I'll reopen this one. Still no progress towards proper layer group support.

**Comment by MarkCCH** [comment]
Did we ever get support for group layers in Web2GIS. It would be super useful. Oddly, some of mine have come through in a group while the bulk of the layers have just been listed above the groups.

**Comment by rajanski** [comment]
just starring

**Comment by M-Sravanthi** [comment]
Facing the same issues of not being able to display layer groups in legend of webmap and popups of grouped layers not showing up.. has this been resolved ?? if yes then ..please guide

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.

**Comment by romanoaguero** [comment]
Hello, has anyone been able to implement the styledLayerControl plugin successfully? I use layers with polygons and it is currently impossible for me.

On the other hand, I have successfully used control.Layers.Tree, which is already included in the new version.

**Comment by stefanocudini** [comment]
> Hello, has anyone been able to implement the styledLayerControl plugin successfully? I use layers with polygons and it is currently impossible for me.
> 
> On the other hand, I have successfully used control.Layers.Tree, which is already included in the new version.

hi @romanoaguero 
unfortunately I don't have much free time(to contribute to qgis2web) lately due to the sad, degrading and time-consuming work environment I'm employed in now -_-
But I can suggest you integrate this plugin:
https://opengeo.tech/maps/leaflet-panel-layers/
 into the code generated by the fantastic qgis2web. The css of the plugin is very simple to customize as you want and is provided with many possible options (see the code of many examples)
Stef

**Comment by stefanocudini** [comment]
> Hello, has anyone been able to implement the styledLayerControl plugin successfully? I use layers with polygons and it is currently impossible for me.
> 
> On the other hand, I have successfully used control.Layers.Tree, which is already included in the new version.

hi @romanoaguero 
unfortunately I don't have much free time lately due to the sad, degrading and time-consuming work environment I'm employed in now.
But I can suggest you integrate this plugin into the code generated by the fantastic qgis2web. The css of the plugin is very simple to customize as you want and is provided with many possible options, see the code of many examples, here:
https://opengeo.tech/maps/leaflet-panel-layers/

**Comment by romanoaguero** [comment]
Thank you so much for answering now I give you a look!! I hope that he regularizes the labor issue successfully !!
