### ISSUE TITLE
Manage when thematic analysis uses calculated fields

### ISSUE THREAD

**Issue by ThomasG77** [tomchadwin/qgis2web#216]
With Leaflet, when I try to make a thematic analysis using calculated field instead of an existing field in the data source, I get a report like below.

```
qgis2web produced an error:

Traceback (most recent call last):
File "/home/thomasg/.qgis2/python/plugins/qgis2web/maindialog.py", line 123, in previewMap
MainDialog.previewLeaflet(self)
File "/home/thomasg/.qgis2/python/plugins/qgis2web/maindialog.py", line 304, in previewLeaflet
visible, cluster, json, params, popup)
File "/home/thomasg/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 94, in writeLeaflet
layerFileName, safeLayerName, minify)
File "/home/thomasg/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 14, in exportJSONLayer
cleanedLayer = writeTmpLayer(i, eachPopup)
File "/home/thomasg/.qgis2/python/plugins/qgis2web/utils.py", line 72, in writeTmpLayer
fieldType = layer.pendingFields().field(field).type()
KeyError: 'POPULATION / (SUPERFICIE / 100)'
```

You should make a message explaining it's not possible to export keeping thematic analysis in this use case or forbid the use case when detected.

For OpenLayers 3, there are no error returned but the overview does not display the thematic analysis, just the layer without any style

**Comment by tomchadwin** [comment]
I can't recreate this yet. Can you give some more details? Is the field a new field or a virtual field? If I create a new virtual field, I don't get that error, so there must be some option you have selected which I have not, to create the error. Can you do a screenshot of your plugin dialog, so I can see your settings?

**Comment by tomchadwin** [comment]
Closed without feedback.
