### ISSUE TITLE
Polygone Style graduated - Symbol selector centroid fill

### ISSUE THREAD

**Issue by michellemoine** [tomchadwin/qgis2web#222]
Hi Tom,

I have a map that is nicely working when symbol selector is set to "simple fill."
Changing that to "centroid fill" will not display in OL3 and throw the following error in Leaflet:

Error

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\maindialog.py", line 123, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\maindialog.py", line 304, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 158, in writeLeaflet
canvas)
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 191, in writeVectorLayer
wfsLayers)
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 592, in graduatedLayer
popFuncs, wfsLayers, categoryStr)
File "C:/Users/hp850/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 672, in graduatedPolygon
border_transp = float(symbolLayer.borderColor().alpha()) / 255
AttributeError: 'QgsCentroidFillSymbolLayerV2' object has no attribute 'borderColor'

Any help is very much appreciated.

**Comment by tomchadwin** [comment]
I'm afraid centroid fill is not supported. I need to catch that error and apply a default style.

To achieve what you need, you'll need to create a new point layer with actual points on the centroids, and then export that.

**Comment by michellemoine** [comment]
Thanks

**Comment by tomchadwin** [comment]
I've just tested this, and I don't get that error. I just get a default style (white fill, black border). Closing for now, unless I can recreate.
