### ISSUE TITLE
Handle unicode column names

### ISSUE THREAD

**Issue by michaelradhuber** [tomchadwin/qgis2web#281]
For people working in other languages than English encoding errors pop up when trying to export maps as leaflet:

`Traceback (most recent call last):
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\maindialog.py", line 134, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\maindialog.py", line 307, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 156, in writeLeaflet
canvas)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 197, in writeVectorLayer
wfsLayers)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 603, in graduatedLayer
popFuncs, wfsLayers, categoryStr)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 689, in graduatedPolygon
borderOpacity)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletScriptStrings.py", line 599, in graduatedPolygonStylesScript
graduatedPolygonStyles = rangeStartScript(valueAttr, r)
File "C:/Users/Michele/.qgis2/python/plugins\qgis2web\leafletScriptStrings.py", line 529, in rangeStartScript
upperValue=r.upperValue())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 25: ordinal not in range(128)`

**Comment by riccardoklinger** [comment]
are your attribute titles maybe filled with "ä","ü" and other common german "Umlauten" please change the attribute title using the table manager plugin.

**Comment by michaelradhuber** [comment]
Thanks that was it!

**Comment by tomchadwin** [comment]
I'm glad you have worked round this issue, but it is still an error: we need to clean the column names as part of the export. I'll leave this issue open.

**Comment by tomchadwin** [comment]
This error might have gone when the Leaflet code was refactored. Please reopen if it reoccurs.
