### ISSUE TITLE
cluster option fails

### ISSUE THREAD

**Issue by riccardoklinger** [tomchadwin/qgis2web#39]
unchecked the option for epsg 3857 layers and press leaflet preview:

Traceback (most recent call last):
  File "/home/ricckli/.qgis2/python/plugins/qgis2web/maindialog.py", line 127, in previewLeaflet
    previewFile = writeLeaflet(utils.tempFolder(), 500, 700, 1, layers, "show all", "", cluster, "", "", "", "", "", "", "", "", 0, 0, json, params)
  File "/home/ricckli/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 413, in writeLeaflet
    print "Cluster: " + unicode(cluster_set[count])
IndexError: list index out of range

export also fails in real export. failing means: expot folder is created, index.html contains complete code but console in firebug does not throw any error and index.html in browser is blank

**Comment by tomchadwin** [comment]
Is this caused by the same as I am asking in #38? What happens if you remove the illegal characters in the attribute names?

**Comment by tomchadwin** [comment]
Ignore last comment. Have just made a commit - can you try current master now? I'm a little confused, as I didn't think this had sorted the problem, but I'm not getting the error any more, and my points are now clustering correctly. What do you get, @riccardoklinger
