### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by rikyperdana** [tomchadwin/qgis2web#393]
I'm using Ubuntu 16.04 + QGIS 2.8 Wien + qgis2web 2.2.0
When I run it, I got this error
I also use the old qgi2leaf and it works perfectly
Any solution?

Error

qgis2web produced an error:

Traceback (most recent call last):
File "/home/riky/.qgis2/python/plugins/qgis2web/maindialog.py", line 164, in previewMap
MainDialog.previewLeaflet(self)
File "/home/riky/.qgis2/python/plugins/qgis2web/maindialog.py", line 374, in previewLeaflet
visible, cluster, json, params, popup)
File "/home/riky/.qgis2/python/plugins/qgis2web/leafletWriter.py", line 96, in writeLeaflet
canvas, restrictToExtent, iface, extent)
File "/home/riky/.qgis2/python/plugins/qgis2web/leafletLayerScripts.py", line 21, in exportJSONLayer
if is25d(layer, canvas, restrictToExtent, extent):
File "/home/riky/.qgis2/python/plugins/qgis2web/utils.py", line 423, in is25d
print traceback.format_exc()
NameError: global name 'traceback' is not defined

**Comment by tomchadwin** [comment]
Urgh, what a stupid bug. Apologies. This is now fixed, so do try downloading current master and letting me know what happens.

However, the error was a problem with error handling. I fully expect it to be replaced with the underlying error, so do report that if you experience one.
