### ISSUE TITLE
Problem with map created from rules 

### ISSUE THREAD

**Issue by news24lor** [tomchadwin/qgis2web#567]
I use last qgis2web version in Mac OS X.

I have a simple shape file with polygon and qgis2web display the polygon very well.
Now I create a thematic map with data from Style window: I use Category, Graduate and qgis2web works.
After I use "Style through rules" in Qgis and I see the map on the screen. I open qgis2web window and I have this error:

qgis2web produced an error:

Traceback (most recent call last):
File "/Users/myusername/.qgis2/python/plugins/qgis2web/maindialog.py", line 318, in previewMap
preview_file = self.createPreview()
File "/Users/myusername/.qgis2/python/plugins/qgis2web/maindialog.py", line 280, in createPreview
dest_folder=utils.tempFolder()).index_file
File "/Users/myusername/.qgis2/python/plugins/qgis2web/olwriter.py", line 86, in write
folder=dest_folder)
File "/Users/myusername/.qgis2/python/plugins/qgis2web/olwriter.py", line 124, in writeOL
popup, json, restrictToExtent, extent, feedback, matchCRS)
File "/Users/myusername/.qgis2/python/plugins/qgis2web/utils.py", line 178, in exportLayers
iface, extent, precision, crs, optimize)
File "/Users/myusername/.qgis2/python/plugins/qgis2web/utils.py", line 192, in exportVector
if is25d(layer, canvas, restrictToExtent, extent):
File "/Users/myusername/.qgis2/python/plugins/qgis2web/utils.py", line 410, in is25d
sl1 = sym.symbolLayer(1)
AttributeError: 'NoneType' object has no attribute 'symbolLayer'

*******

It's impossible to create map on qgis2web using the option 'Style through rules' in Styles window.

Is this a bug?

Thanks
Lorenzo

**Comment by tomchadwin** [comment]
I don't know the 'Style through rules' option. Rule-based renderers are supported, but this sounds like something slightly different. Are yo uable to upload a layer and QGIS project file so we can take a look?

**Comment by news24lor** [comment]
Sorry but in the italian version of QGIS the name is 'Stile Tramite regole'.
This is the screenshot

![qgis_problem](https://user-images.githubusercontent.com/33484600/32550640-31e1a24a-c48e-11e7-8cc3-e440b34e21e7.jpg)

**Comment by news24lor** [comment]
Hi
This is the file with error. It's a qgs file with only one geojson file with polygon: it has five fields.
The rules style is simple. If you open qgis2web you have the error.

Thanks in advance
Lorenzo


[qgis2web_error.zip](https://github.com/tomchadwin/qgis2web/files/1457183/qgis2web_error.zip)

**Comment by news24lor** [comment]
Fixed! Now it works...
Thank you very much

**Comment by tomchadwin** [comment]
Splendid. Thanks for letting us know.
