### ISSUE TITLE
Error in Version 2.32

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#585]
After updating to latest version 2.32 I get this error as soon as i choose QGIS2WEB:

2017-12-04T17:51:11	1	Traceback (most recent call last):
			  File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\qgis2web.py", line 58, in run
			    self.dlg = MainDialog(self.iface)
			  File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\maindialog.py", line 86, in __init__
			    self.setupUi(self)
			  File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\ui_maindialog.py", line 142, in setupUi
			    uitime = Ui_TimeDialog(self.tabWidget, MainDialog)
			  File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 54, in __init__
			    self.populate_layers_and_groups(self)
			  File "C:/Users/MAP/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 80, in populate_layers_and_groups
			    testDump = layer.rendererV2().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'

Reinstalling version 2.31 removes the error!

I am running QGIS 2.18.14 in Win 64 bit

**Comment by tomchadwin** [comment]
Can you try putting a # at the beginning of line 92, so that it becomes:

```python
                    # raise
```

Does that fix it?

**Comment by magerlin** [comment]
Yes adding the # in ui_timedialog.py do fix it....

I have noticed the Time tab in Qgis2web but I must have missed any information on this new feature - is it described somewhere...

**Comment by enadol** [comment]
It fixed it!

**Comment by tomchadwin** [comment]
Thanks for finding this bug and reporting it so quickly. I've committed that fix to the `QGIS2` branch?
