### ISSUE TITLE
Build resources

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#586]

**Comment by tomchadwin** [comment]
First problem I can't figure out. Try current master. I get:

```
Couldn't load plugin 'qgis2web' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 29, in 
    from .maindialog import MainDialog
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 67, in 
    from .configparams import (getParams,
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\configparams.py", line 22, in 
    from .exporter import EXPORTER_REGISTRY
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\exporter.py", line 32, in 
    from .feedbackDialog import Feedback
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\feedbackDialog.py", line 34, in 
    "ui_feedback_dialog.ui"))
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\PyQt5\uic\__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 33, in 
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 2.99.0-Master Master, 32ba5bf23f 

Python Path:
C:/OSGEO4~1/apps/qgis-dev/./python/plugins\processing
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary-master
C:\Users\tchadwin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary-master\extlibs
```

**Comment by tomchadwin** [comment]
Here's the solution to that problem:

https://gis.stackexchange.com/questions/139625/qgis-plugin-problems-importing-resources-resources-rc-file-plugin-doesnt-l

**Comment by tomchadwin** [comment]
No longer using a resources file.

**Comment by mtravis** [comment]
@tomchadwin I hit the same problem. Is it really as simple as removing the reference to the resources_rc.py in QGIS 3.* plugins?

**Comment by mtravis** [comment]
Just tested this. Turns out it was that simple.
