### ISSUE TITLE
Uncaught UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 48: ordinal not in range(128)


### ISSUE THREAD

**Issue by peter-shr** [tomchadwin/qgis2web#592]
Steps to reproduce
 1. First - properties
 2. Second - Update preview
 3. Third - Export

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\qgis2web\maindialog.py", line 340, in saveMap
    result = self.exporter.postProcess(results, feedback=self.feedback)
  File "C:/Users/USER/.qgis2/python/plugins\qgis2web\exporter.py", line 142, in postProcess
    feedback.setCompleted('Exported to {}'.format(self.folder))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 48: ordinal not in range(128)

```
qgis2web 2.33.0, QGIS 2.14.21-Essen on Windows 10

**Comment by tomchadwin** [comment]
I've committed a possible fix to the QGIS2 branch. Can you download, test, and report back?
