### ISSUE TITLE
Uncaught ValueError: invalid literal for int() with base 10: 'Outer Bluegrass'


### ISSUE THREAD

**Issue by rihorn** [tomchadwin/qgis2web#593]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/ian.horn/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 230, in saveLayerTimeToComboSettings
    self.populateMinMax()
  File "C:/Users/ian.horn/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 246, in populateMinMax
    dateout = datestr[0:4] + "-" + datestr[4:6] + "-" + datestr[6:8]
ValueError: invalid literal for int() with base 10: 'Outer Bluegrass'

```
qgis2web 2.23.1, QGIS 2.18.14 on Windows 7

**Comment by tomchadwin** [comment]
Can you upload your layer, and let us know which fields you are selecting on the `Time` tab?

**Comment by tomchadwin** [comment]
Ping @ruz76

**Comment by tomchadwin** [comment]
Closing without feedback.
