### ISSUE TITLE
'qgis2web' 3.0 not installing due to trying to import PyQt5.QtWebKitWidgets

### ISSUE THREAD

**Issue by geojoek** [tomchadwin/qgis2web#625]
Howdy! Thank you for all of the great work on this plugin!

Getting this error when trying to install / load qgis2web 3.0 on QGIS 3.0.0 Girona for Ubuntu (ubuntugis):

Couldn't load plugin 'qgis2web' due to an error when calling its classFactory() method 

ImportError: No module named 'PyQt5.QtWebKitWidgets' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/joe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/joe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 30, in 
    from qgis2web.maindialog import MainDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/joe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 56, in 
    from qgis.PyQt.QtWebKitWidgets import QWebView, QWebInspector, QWebPage
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtWebKitWidgets.py", line 26, in 
    from PyQt5.QtWebKitWidgets import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'PyQt5.QtWebKitWidgets'

Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
QGIS version: 3.0.0-Girona Girona, aaf7c00 

Python Path:
/usr/share/qgis/python
/home/joe/.local/share/QGIS/QGIS3/profiles/default/python
/home/joe/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/joe/.local/share/QGIS/QGIS3/profiles/default/python
/home/joe/Downloads/2018_Richard_Heeley

**Comment by stefanocudini** [comment]
hi @tomchadwin  how are you!?

I have the same issue in my new qgis3 on ubuntu 17.10

**Comment by tomchadwin** [comment]
You need to make sure that QtWebKit for Qt5 is installed, together with its Python3 bindings. I'm afraid I can't offer any more expertise than that, as I'm a Windows user. Please do reply here if you manage to figure it out.

**Comment by tomchadwin** [comment]
Can you try this:

```shell
apt-get -y install python3-pyqt5.qtwebkit libqt5webkit5-dev
```

**Comment by JakobMiksch** [comment]
had the same problem, @tomchadwin solution worked for me as well

**Comment by Pablohn26** [comment]
To fix this problem on Fedora you have to install the package with 

> sudo dnf install python3-qt5-webkit.x86_64

**Comment by reginaldc** [comment]
the packages python3-pyqt5.qtwebkit and libqt5webkit5-dev are already installed and I still got the error.
I get this error also with geopunt plugin

**Comment by tomchadwin** [comment]
@reginaldc What's your distribution/architecture?

**Comment by reginaldc** [comment]
Hi Tom,

I am running ubuntu cosmic.
The version of QGIS is 3.4.

Regards,


Reginald Carlier
Deskundige GIS
Gemeente Ingelmunster, Oostrozebekestraat 4, 8770 Ingelmunster
T+32 51 33 74 39www.ingelmunster.be
Schrijf je in op onze nieuwsbrief!
Raadpleeg onze disclaimer 
Van: Tom Chadwin [mailto:notifications@github.com]
Verzonden: maandag 26 november 2018 12:49
Aan: tomchadwin/qgis2web
CC: Reginald Carlier; Mention
Onderwerp: Re: [tomchadwin/qgis2web] 'qgis2web' 3.0 not installing due to trying to import PyQt5.QtWebKitWidgets (#625)


@reginaldc<https://github.com/reginaldc> What's your distribution/architecture?

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
