### ISSUE TITLE
qgis2web time extension python error

### ISSUE THREAD

**Issue by noella08** [tomchadwin/qgis2web#626]
I want to add a time slider to my qgis2web produced webmap. I am first trying it out using the chronogisnet data set. I have downloaded the "qgis2web_time_extension-master" and replaced the ui_timedialog.py file and also edited the ui_maindialog.py as it says to in the Readme . However, when i try to "add time" i get a python error

_**StopIteration**
Traceback (most recent call last):
File "C:/Users/Ikatutsi/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 296, in saveMap
self.saveOLMap()
File "C:/Users/Ikatutsi/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 431, in saveOLMap
root, dirs, files = os.walk(dir).next()
StopIteration_

Iam using qgis2.18.16 with 2.33.1 qgis2web version.

**Comment by tomchadwin** [comment]
Firstly, I *think* that the time extension has been merged into qgis2web, so you don't have to overwrite anything. It should be there already. Can you try uninstalling qgis2web and reinstalling it, then investigating without manually installing the time extension?

**Comment by tomchadwin** [comment]
OK, thanks. Any ideas, @ruz76?

**Comment by ruz76** [comment]
I have seen that error previously and I think that it can happen in a case that project is not saved or normal export was not created before adding the time. Could you please try to save project, export map and then add the time and let me know if the error is still here. Thank you.

**Comment by noella08** [comment]
I had not exported the map first before adding the time. it works fine now.
no error. Thanks

*Kind regards,*

*Katutsi Immaculate,*
*Geo-information specialist / Land surveyor*
*+256 785 938304*
