### ISSUE TITLE
Parsing nested tree grouped layers cause error on running plugin

### ISSUE THREAD

**Issue by marcobra** [tomchadwin/qgis2web#65]
With release 0.13.2

```
Group -
           - a 
           - b
```
if layer are grouped in layer side frame as above i get this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 175, in saveOL
    layers, groups, popup, visible, json, cluster, labels = self.getLayersAndGroups()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 225, in getLayersAndGroups
    if item.json:
AttributeError: 'TreeGroupItem' object has no attribute 'json'
```

If i pull out the file "a" from the group and i elaborate only the file "a" the error disappear...
```
- a
Group -
           - b
```

Thank

**Comment by tomchadwin** [comment]
Does this fail in qgis-ol3?

**Comment by marcobra** [comment]
With release 0.13.2
after this previuos reported fail now plugin give me at startup
```
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/qgis2web.py", line 51, in run
    dlg = MainDialog()
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 45, in __init__
    self.populateConfigParams(self)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2web/maindialog.py", line 138, in populateConfigParams
    dlg.paramsTreeOL.itemWidget(subitem, 1).setCurrentIndex(comboSelection)
TypeError: QComboBox.setCurrentIndex(int): argument 1 has unexpected type 'unicode'
```
and the suggested, python console:
```
from PyQt4.QtCore import QSettings
QSettings().remove("Extent")
QSettings().remove("Base layer")
QSettings().remove("Template")
```
do not solve...

**Comment by tomchadwin** [comment]
I'll reopen that issue and discuss it there.

**Comment by tomchadwin** [comment]
It doesn't fail in qgis-ol3. It seems that the extra per-layer settings I've added are confused by the presence of layer groups. I'll look into it.

**Comment by tomchadwin** [comment]
Hopefully fixed in master. Please test - the fix might have caused other problems with per-layer settings, but I've not spotted them yet.
