### ISSUE TITLE
Export Project in Processing Toolbox Behavior!!

### ISSUE THREAD

**Issue by shivareddyiirs** [tomchadwin/qgis2web#730]
It does not ask for export directory and export to default address. Is this intended? I feel user should be asked the destination folder or FTP location.

**Comment by tomchadwin** [comment]
It's a long time since I looked at the processing algorithm. Doesn't it take settings in some kind of list?

**Comment by shivareddyiirs** [comment]
Once we double click on the _export project_ toolbox , it directly runs without prompting anything to the user I tasted latest version

**Comment by tomchadwin** [comment]
I really didn't think it was working. I get an error. Which version are you using? Are you still on 2.x?

**Comment by shivareddyiirs** [comment]
I am using QGIS 3.6

**Comment by tomchadwin** [comment]
I get "Problem executing algorithm":

```
Traceback (most recent call last): File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2webAlgorithm.py", line 108, in processAlgorithm writer.write(iface, write_folder) File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write folder=dest_folder) File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 137, in writeOL mapSettings.destinationCrs().authid()) File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olLayerScripts.py", line 39, in writeLayersAndGroups getFeatureInfo)): TypeError: zip argument #4 must support iteration
```

Doesn't that sound like an error you fixed with a PR?

**Comment by shivareddyiirs** [comment]
Yes. In the latest version of plugin this error is not coming

**Comment by tomchadwin** [comment]
Ah, I must somehow have overwritten your PR in my local copy. Working now.

**Comment by shivareddyiirs** [comment]
The code in qgis2webAlgorithm.py at line no. 107 in  `write_folder = exporter.exportDirectory()`  is the reason for said behavior. 
This variable value should be assigned from the parameter. Similarly it can be done for other two algorithms.

**Comment by andreaordonselli** [comment]
@shivareddyiirs I opened this request on [gis.stack](https://gis.stackexchange.com/questions/480114/run-processing-without-open-qgis-for-specific-project) but no one responded to me, can you look at my code and correct it? 

I would simply like the user to set the export parameters in qgis2web interface and do a first export with saving the .qgz. 
Then I would like to launch "Export project" from Toolbox to have the same export (same path, same choices made in interface)
