### ISSUE TITLE
qgis2web plugin does not install

### ISSUE THREAD

**Issue by VojtechSlavnik** [tomchadwin/qgis2web#749]
Trying to install qgis2web from within QGIS 3.6.2.  It is not installing:

Couldn't load plugin 'qgis2web' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/watkec/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/watkec/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2web.py", line 30, in 
    from qgis2web.maindialog import MainDialog
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/?????/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 57, in 
    from qgis.PyQt.QtWebKitWidgets import QWebView, QWebInspector, QWebPage
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/qgis/PyQt/QtWebKitWidgets.py", line 26, in 
    from PyQt5.QtWebKitWidgets import *
  File "/app/share/qgis/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

Python version: 3.7.3 (default, Nov 10 2011, 15:00:00) [GCC 8.3.0] 
QGIS version: 3.6.2-Noosa Noosa, 656500e0 

There are numerous mentions of this issue on the web with no apparent solution.

**Comment by tomchadwin** [comment]
> There are numerous mentions of this issue on the web with no apparent solution.

You need QtWebkit. Whether this is available depends on your OS. Investigate how to install it on your system. Once installed, qgis2web should run.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which excluded WIKI and Preview functionality for Linux users who are unable to install and use QtWebKit, **so the plugin will launch and be usable without these features**

Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
