### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by xmxo** [tomchadwin/qgis2web#750]

**Comment by xmxo** [comment]
Qgis Version 3.6 and Qgis2web 3.7 on win64bits
Traceback (most recent call last):
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 336, in saveMap
    feedback=self.feedback)
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 130, in writeOL
    popup, json, restrictToExtent, extent, feedback, matchCRS)
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 220, in exportLayers
    iface, extent, precision, crs, optimize)
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 233, in exportVector
    cleanLayer = writeTmpLayer(layer, restrictToExtent, iface, extent)
  File "C:/Users/p12148/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 162, in writeTmpLayer
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 100
