### ISSUE TITLE
Vector tiles: "The field 'tiles' is required but not found. This is invalid TileJSON."

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#814]
I can't understand quite what causes this. I initially load a remote MBVT source using the Vector Tiles Reader plugin. I can then export via qgis2web. However, I then import some QML styles to some of the VT layers, and change the order of the layer groups. When I then try to export with qgis2web, I get this error:

```
Traceback (most recent call last):
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in saveMap
    feedback=self.feedback)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 91, in write
    folder=dest_folder)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 138, in writeOL
    mapSettings.destinationCrs().authid())
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olLayerScripts.py", line 50, in writeLayersAndGroups
    vtLayers)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olLayerScripts.py", line 120, in layerToJavascript
    return getVT(vts), vtLayers
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olLayerScripts.py", line 454, in getVT
    tile_url = json.tiles()[0].split("?")[0]
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\tile_json.py", line 107, in tiles
    tiles = self._get_value("tiles", is_array=True, is_required=True)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\tile_json.py", line 130, in _get_value
    raise RuntimeError("The field '{}' is required but not found. This is invalid TileJSON.".format(field_name))
RuntimeError: The field 'tiles' is required but not found. This is invalid TileJSON.
```

We use VTR's TileJSON function to construct the raw PBF path needed to add VTRs to webmaps. The error logged in the VTR log is:

```
2019-09-25T17:39:49     WARNING    Request failed: Protocol "p" is unknown
2019-09-25T17:39:49     WARNING    Loading TileJSON failed (P:/transfer/OS-Open-Zoomstack.mbtiles): (, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), )
```

Where does that path come from? I don't recognize it at all. @mnboos?

**Comment by mnboos** [comment]
2019-09-25T17:39:49     WARNING    > Loading TileJSON failed (P:/transfer/OS-Open-Zoomstack.mbtiles): (, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), )

Here it says it's from an mbtiles file, which is basically a sqlite database. In there, you should find the json value, which is used for the TileJSON. Could you check that with a sqlite viewer?

**Comment by tomchadwin** [comment]
OK, but I'm using a remote server source of tiles - ie the first tab in the dialog. Is it possible that if both first and second tabs are filled in (in my case, possibly a historic artefact of having used the plugin for a long time), there is some confusion as to whether the connection local or remote?

**Comment by tomchadwin** [comment]
I did have some settings in the MBTiles tab. I've cleared them out. The odd P:\ error in the VTR log has now gone, but the exception is still raised.

Further testing seems to show that dragging the folder to reorder the srtacking of the VT layers is *not* what triggers this error. Loading a QML style for one of the VT layers is.

So the steps to recreate (for me are):

1. Add VT *server* layers to canvas
2. Export qgis2web webmap - works
3. Apply QML to a VT layer
4. Export qgis2web webmap - fails with the exception in the first post here

**Comment by tomchadwin** [comment]
> The odd P:\ error in the VTR log has now gone

No, wait, that error is back again:

```
2019-09-26T09:52:30     WARNING    Request failed: Protocol "p" is unknown
2019-09-26T09:52:30     WARNING    Loading TileJSON failed (P:/transfer/OS-Open-Zoomstack.mbtiles): (, JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), )
```

**Comment by tomchadwin** [comment]
OK, I'm closing in on this one...

qgis2web identifies a QGIS layer a vector ties layer (ie one created by the Vector Tiles Reader QGIS plugin) by retrieving that layer's custom property:

```
layer.customProperty("VectorTilesReader/vector_tile_url")
```

When I use VTR to connect to a MBVT server, and add its layers, this custom property indeed shows the URL:

```
https://s3-eu-west-1.amazonaws.com/tiles.os.uk/data/vector/open-zoomstack/config.json
```

However, if I then apply a saved QML style to one of the layers in the VT stack, that layer's custom property changes to the incorrect (and pretty mystifying) local path:

```
P:/transfer/OS-Open-Zoomstack.mbtiles
```

So how can that custom property change?

**Comment by mnboos** [comment]
Is this path anywhere within the saved QML?

**Comment by tomchadwin** [comment]
I think you nailed it!

```
    <property key="VectorTilesReader/vector_tile_source" value="OS-Open-Zoomstack.mbtiles"/>
    <property key="VectorTilesReader/vector_tile_url" value="P:/transfer/OS-Open-Zoomstack.mbtiles"/>
```

Now why on earth are those values in there?! I'll try deleting them, and see if that fixes it (guessing it will).

Thanks so much!

**Comment by tomchadwin** [comment]
Yes, pretty sure that was the issue. I still have a problem, because if I try to load a QML to style a VTR layer, it overrides the customProperties, so qgis2web no longer detects the layers as VTR layers. That seems to have been at the heart of the issue. If the relevant customProperties are not there in the QML at all, *but some customProperties are*, it removes the whole customProperty.

Thanks again for all the help. Very much appreciated.

**Comment by andreaordonselli** [comment]
In version [4.3.0](https://github.com/qgis2web/qgis2web/releases/tag/v4.3.0) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.
Best regards.
