### ISSUE TITLE
Broken export after QGIS 3.10 update.

### ISSUE THREAD

**Issue by esolak** [tomchadwin/qgis2web#824]
After upgrading to version of 3.10 of QGIS yesterday, I started getting the following python errors on OSX Catalina when trying to export the project.

```
2019-10-30T10:49:30     WARNING    Traceback (most recent call last):
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 323, in previewMap
              preview_file = self.createPreview()
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 286, in createPreview
              dest_folder=utils.tempFolder()).index_file
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 91, in write
              folder=dest_folder)
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 130, in writeOL
              popup, json, restrictToExtent, extent, feedback, matchCRS)
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 220, in exportLayers
              iface, extent, precision, crs, optimize)
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 234, in exportVector
              if is25d(layer, canvas, restrictToExtent, extent):
              File "/Users/ercan/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py", line 490, in is25d
              sl1 = sym.symbolLayer(1)
             IndexError: 1
```

**Comment by tomchadwin** [comment]
That looks like an issue which has since been fixed. Can you try upgrading to 3.10.0 of qgis2web, released today. Please report back.

**Comment by esolak** [comment]
Updated the plugin. Works ! Thanks for the quick response.

**Comment by tomchadwin** [comment]
Splendid! Thanks for reporting back.
