### ISSUE TITLE
Error when exporting with Processing

### ISSUE THREAD

**Issue by pcav** [tomchadwin/qgis2web#843]
`Traceback (most recent call last): File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2webAlgorithm.py", line 102, in processAlgorithm writer.cluster) = self.getLayersAndGroups() File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/qgis2webAlgorithm.py", line 118, in getLayersAndGroups layer.wbbType() != QgsWkbTypes.NoGeometry) and AttributeError: 'QgsVectorLayer' object has no attribute 'wbbType' `

**Comment by pcav** [comment]
QGIS 3.10, updated qgis2web
Thanks.

**Comment by pcav** [comment]
Thanks Tom!
