### ISSUE TITLE
mapbox GL JS   error

### ISSUE THREAD

**Issue by pokmo** [tomchadwin/qgis2web#851]
When you click on the button'Mapbox GL JS', the program freezes and a message appears in the log:

"  UnboundLocalError: local variable 'new_pop' referenced before assignment "

**Comment by tomchadwin** [comment]
We need more details. Can you paste the whole error message from the log? It should include a file and line number. In order to investigate fully, we probably also need you project and layer files. Can you zi them and drag-n-drop them onto a reply on this thread?

**Comment by pokmo** [comment]
2020-01-29T12:27:40     WARNING    Traceback (most recent call last):
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 190, in changeFormat
              self.autoUpdatePreview()
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in autoUpdatePreview
              self.previewMap()
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
              preview_file = self.createPreview()
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
              dest_folder=utils.tempFolder()).index_file
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 104, in write
              folder=dest_folder)
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxWriter.py", line 296, in writeMapbox
              useOSMB, vtSources, layers)
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxLayerScripts.py", line 52, in writeVectorLayer
              vts)
              File "C:/Users/andriy.dovgyy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\mapboxLayerScripts.py", line 371, in getPopups
              return new_pop
             UnboundLocalError: local variable 'new_pop' referenced before assignment

**Comment by pokmo** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/33067259/73349024-18af7880-4293-11ea-8a18-8d20b572dd30.jpg)

**Comment by pokmo** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/33067259/73349139-53191580-4293-11ea-8429-c9f077500c63.jpg)

**Comment by tomchadwin** [comment]
Thanks but we do also need the layer and project files - can you upload them here? Thanks.

**Comment by pokmo** [comment]
Playback steps:
1. Launched QGIS 3.10.2-A Coruña
2. Created a temporary polygonal or other layer. named "temporary layer"
3. Pressed the button of plugin "Create web map" v.3.12.1
4. The plugin window has opened.
5. Pressed the switch "Mapbox GL JS"
6. The cursor in the form of an arrow was transformed into a load indicator.
7. A window appeared with a python error , 
with text from previous message
8. In the progress of the plugin itself, an endless message:
   "Creating Mapbox map...
    Exporting libraries... done
    Writing CSS... done
    Exporting temporary layerr to JSON... done
    Writing temporary layer as JSON..."

**Comment by pokmo** [comment]
temporary layer   .zip

**Comment by tomchadwin** [comment]
I'll try to reacreate - thanks. One question: the Python error relates to the generation of the popup containing feature attribute data. Given that this is a scratch layer, have you created fields? I've never tried qgis2web with scratch layers, so I don't have any experience of this.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by tomchadwin** [comment]
Released as 3.13.0 and pushed to QGIS plugins repo.
