### ISSUE TITLE
Error when trying to export to Mabox GL Js

### ISSUE THREAD

**Issue by baditaflorin** [tomchadwin/qgis2web#888]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

Using Qgis 3.4.1 installed via apt get qgis
Fresh install of Qgis. 
Plugin installed via Qgis. 
OS: Linux mint 19.3 

```
2020-05-20T21:14:43     WARNING    Traceback (most recent call last):
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 190, in changeFormat
              self.autoUpdatePreview()
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 334, in autoUpdatePreview
              self.previewMap()
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
              preview_file = self.createPreview()
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 300, in createPreview
              dest_folder=utils.tempFolder()).index_file
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxWriter.py", line 104, in write
              folder=dest_folder)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxWriter.py", line 296, in writeMapbox
              useOSMB, vtSources, layers)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxLayerScripts.py", line 145, in writeVectorLayer
              mblayers = getLayerStyle(layer)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/mapboxStyleScripts.py", line 43, in getLayerStyle
              mapboxStyle = bridgestyle.qgis.layerStyleAsMapbox(layer)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/__init__.py", line 50, in layerStyleAsMapbox
              geostyler, icons, warnings = togeostyler.convert(layer)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 32, in convert
              geostyler = processLayer(layer)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 76, in processLayer
              rules.extend(processRule(rule, None, layer.opacity(), layer))
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 453, in processRule
              symbolizers = _createSymbolizers(rule.symbol(), layerOpacity)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 605, in _createSymbolizers
              symbolizer = _createSymbolizer(sl, opacity)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 625, in _createSymbolizer
              symbolizer = _simpleFillSymbolizer(sl, opacity)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 936, in _simpleFillSymbolizer
              sl, "outline_width", QgsSymbolLayer.PropertyStrokeWidth
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 572, in _symbolProperty
              v = _handleUnits(v, units, propertyConstant)
              File "/home/florin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/togeostyler.py", line 519, in _handleUnits
              if units in ["Point", QgsUnitTypes.RenderUnit.RenderPoints]:
             AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints'
```

**Comment by tomchadwin** [comment]
Can you upload your layer and project files?

**Comment by tomchadwin** [comment]
Closing without feedback. Since this is an error within bridgestyle, do open an issue at https://github.com/GeoCat/bridge-style/issues, together with your style file.
