### ISSUE TITLE
qgis2web and maptiler pluggins compatible ?

### ISSUE THREAD

**Issue by jipexu** [tomchadwin/qgis2web#907]
HI

I use some data from maptiler
<img width="798" alt="Capture d’écran 2020-07-25 à 11 37 23" src="https://user-images.githubusercontent.com/328101/88453892-633d3680-ce6b-11ea-97b8-1371fff1934a.png">

when i ask for preview (even with only topo group checked) i get this Python  errors
i dont see what is wrong ?...

Une erreur est survenue lors de l'éxécution du code Python: 

```
TypeError: cannot unpack non-iterable NoneType object 
Traceback (most recent call last):
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 337, in previewMap
    preview_file = self.createPreview()
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 300, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 91, in write
    folder=dest_folder)
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 138, in writeOL
    mapSettings.destinationCrs().authid())
  File "/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olLayerScripts.py", line 50, in writeLayersAndGroups
    vtLayers)
TypeError: cannot unpack non-iterable NoneType object


Version de Python : 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
Version de QGIS : 3.14.0-Pi Pi, 9f7028fd23 

Chemin Python :
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python
/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.14.app/Contents/Resources/python
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/Users/jpb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/jpb/Documents/Chine/bd_chine
```
.
Thanks

**Comment by akuckartz** [comment]
https://github.com/maptiler/qgis-maptiler-plugin

**Comment by jipexu** [comment]
@akuckartz need open issue there ? https://github.com/maptiler/qgis-maptiler-plugin

**Comment by akuckartz** [comment]
@jipexu I have no idea. Maybe create an issue there and link to this one.

**Comment by jipexu** [comment]
work for leaflet export
not work for openlayers export
