### ISSUE TITLE
cannot install qgis2web on QGIS 3.22.1(Osgeo4W installation)

### ISSUE THREAD

**Issue by reginaldc** [tomchadwin/qgis2web#986]
Hi,

When I try to install qgis2web on the latest qgis version (I am using Osgeo4W on windows 10), I get an error which I have pasted below. Is there a python module that I have to install in my python environment to make this plugin work?
On QGIS 3.22.0, standalone version, the plugin installs fine. It seems like it is an OSGeo4W issue?

Regards,

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\xmltodict.py", line 11, in 
    from cStringIO import StringIO
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\__init__.py", line 28, in classFactory
    from .qgis2web import Qgis2Web
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\qgis2web.py", line 29, in 
    from qgis2web.maindialog import MainDialog
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\maindialog.py", line 67, in 
    from qgis2web.olwriter import OpenLayersWriter
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\olwriter.py", line 35, in 
    from qgis2web.olScriptStrings import (measureScript,
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\olScriptStrings.py", line 1, in 
    from . import xmltodict
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/reginaldc/AppData/Roaming/QGIS/QGIS3\profiles\biawo/python/plugins\qgis2web\xmltodict.py", line 14, in 
    from StringIO import StringIO
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Python27\ArcGIS10.5\Lib\StringIO.py", line 40
    raise ValueError, "I/O operation on closed file"
                    ^
SyntaxError: invalid syntax

**Comment by reginaldc** [comment]
It looks like the python environment of the ArcGis installation is causing this problem.
I have to contact the sysadmin in order to fix this.

Regards,
