### ISSUE TITLE
Typerror and blank map on OpenLayers export after adding Graduated Symbology Colours

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [tomchadwin/qgis2web#999]
Hi,

Layer styling via Properties --> Symbology throws a javascript error and shows a blank map (just the zoom controls are visible). I graduated a colour scale using a ramp per country. Then custom edited some countries to specific colours. The unedited World map (added using "world" in the coordinate box) exports OK to Open Layers. It's only when the styling is added that the error occurs. It exports OK to Leaflet.

qgis2web Version: 3.16.0

QGIS version: 3.24.3-Tisler

Browser error:  

```
Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at categories_WorldMap_0 (WorldMap_0_style.js:6:30)
    at style_WorldMap_0 (WorldMap_0_style.js:1939:13)
    at e.<anonymous> (VectorLayer.js:387:26)
    at e.prepareFrame (VectorLayer.js:401:13)
    at e.render (Layer.js:209:27)
    at e.renderFrame (Composite.js:111:33)
    at e.renderFrame_ (PluggableMap.js:1120:24)
    at e.<anonymous> (PluggableMap.js:175:18)
```

![Screenshot_20220608_134653](https://user-images.githubusercontent.com/951566/172621305-49a5c830-d259-4aa5-b7d6-7e8bcba4245b.jpg)
![Screenshot_20220608_134626](https://user-images.githubusercontent.com/951566/172621369-052d6553-1f39-468c-ac6c-2f694f6690ff.jpg)

First QGIS file exports OK - https://files.michaelzfreeman.org/World%201.qgz

The same file with added styling fails to export or preview - https://files.michaelzfreeman.org/World%202.qgz

**Comment by andreaordonselli** [comment]
in addition to the qgz file can you also provide the data? maybe with a unique project zip?
